version: '9.4'
services:
  nginx_service:
    build:
      context: .
      dockerfile: nginx
    image: nginx_html_template:1
    ports:
    -  "8888:80"
    volumes:
    -  nginx_data:/data
    networks:
    - network1
volumes:
  nginx_data:
networks:
  network1:

