version: '3.8'
services:
  wordpress-wordpress:
    image: wordpress:latest
    volumes:
    - wordpress-data:/var/www/html
    networks:
    - network1
    ports:
    - "8888:80"
volumes:
  wordpress-data:
networks:
  network1:
    driver: bridge
